// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5u40FuoCNtHCX46Uosn9upOI1TQX-LnQ',
    appId: '1:659796885543:android:294b4aaaf998e088a54e02',
    messagingSenderId: '659796885543',
    projectId: 'imposing-carver-476010-k3',
    storageBucket: 'imposing-carver-476010-k3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChMuHHPP7MeFkf-4TB1Wd1MyPsmJa64so',
    appId: '1:659796885543:ios:a7f099fdbcd284f9a54e02',
    messagingSenderId: '659796885543',
    projectId: 'imposing-carver-476010-k3',
    storageBucket: 'imposing-carver-476010-k3.firebasestorage.app',
    iosBundleId: 'com.example.goeventApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvFJS8hF1vd_Rfzxgl9PUe-a-nIeWpaeg',
    appId: '1:659796885543:web:9eb46edbc640ef08a54e02',
    messagingSenderId: '659796885543',
    projectId: 'imposing-carver-476010-k3',
    authDomain: 'imposing-carver-476010-k3.firebaseapp.com',
    storageBucket: 'imposing-carver-476010-k3.firebasestorage.app',
    measurementId: 'G-YDSM7B9ELS',
  );

}